spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car
    username: root
    password: '000000'
  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
#    开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    自动驼峰
    map-underscore-to-camel-case: true

#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
